name: Go CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build & Test Go Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'  # Use the latest stable version

      - name: Cache Go Modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Create .env file
        run: |
          echo "DNS_SERVER_PORT=${{ secrets.DNS_SERVER_PORT }}" >> .env
          echo "DNS_LOG_FILE=${{ secrets.DNS_LOG_FILE }}" >> .env
          echo "DNS_SERVER_IP=${{ secrets.DNS_SERVER_IP }}" >> .env
          cat .env  # Debugging: Print .env to verify contents

      - name: Load Environment Variables
        run: echo "DOTENV_LOADED=1" >> $GITHUB_ENV  # Ensure env file is created

      - name: Install Dependencies
        run: go mod tidy

      - name: Run Unit Tests
        env:
          DNS_SERVER_PORT: ${{ secrets.DNS_SERVER_PORT }}
          DNS_LOG_FILE: ${{ secrets.DNS_LOG_FILE }}
          DNS_SERVER_IP: ${{ secrets.DNS_SERVER_IP }}
        run: go test ./tests -v

      - name: Build Application
        run: go build -o dns-server ./src

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dns-server-binary
          path: ./dns-server
